title: 'Landed'
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
menu:
    - url: '#'
      text: 'Sign Up'
      classes: 'button primary'
taxonomies: [category, tag, pagetype]