title: default
'@extends':
    type: default

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          
          fields:
            header.hero_image:
              type: pagemediaselect
              label: Hero Image
              help: The name and extension of an image in this folder
            header.subheading:
              type: text
              label: Subheading
              help: Just write something
            header.meta_description:
              type: text
              label: Meta Description
              help: Used for things like Twitter
            
            header.spotlight:
              type: fieldset
              title: Spotlight Info
              help: Fill this out if you want this to appear on a Home page
              info: 
              text: 
              icon: 
              collapsed: true     # Initial state of fieldset (see collapsible option)
              collapsible: true    # Whether one can expand the fieldset or not 
              fields:
                header.spotlight.image:
                  type: pagemediaselect
                  label: Spotlight Background Image
                  help: 
                header.spotlight.headline:
                  type: text
                  label: Headline
                  help: 
                header.spotlight.subheading:
                  type: text
                  label: Subheading
                  help: 
                header.spotlight.blurb:
                  type: textarea
                  label: Blurb
                  help: 
                header.spotlight.button.text:
                  type: text
                  label: Spotlight Button Link Text
                  help: Used when this page is linked on Home pages
            header.blog:
              type: fieldset
              title: Blog Info
              help: Fill this out if you want this to appear on a Blog page
              info: 
              text: 
              icon: 
              collapsed: true     # Initial state of fieldset (see collapsible option)
              collapsible: true    # Whether one can expand the fieldset or not 
              fields:
                header.blog.button.text:
                  type: text
                  label: Blog Button Text
                  help: Used when this page is linked on Blog pages
                header.blog.preview:
                  type: textarea
                  label: Preview
                  help: Used in place of an automatic summary
              
            
                


